version: "3.3"

services:

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3
    restart: always
    networks:
      - internal
    ports:
      - 5672:5672

  redis:
    env_file: .env
    image: redis
    volumes:
      - ./redis/logs:/log
      - ./redis/dir:/data
    command: redis-server --requirepass ${R_DB_PW}
    restart: always
    networks:
      - internal
    ports:
      - 6379:6379

  centrifugo:
    container_name: centrifugo
    image: centrifugo/centrifugo:latest
    volumes:
      - ./centrifugo/config.json:/centrifugo/config.json
    command: centrifugo -c config.json
    restart: always
    networks:
      - internal
    ports:
      - 8000:8000
    ulimits:
      nofile:
        soft: 65535
        hard: 65535

  lab:
    build:
      context: ./app
    env_file: .env
    environment:
      SERVICES: lab
      PORT: 3210
    depends_on:
      - rabbitmq
    networks:
      - internal
    ports:
      - 3210:3210

  api:
    build:
      context: ./app
    env_file: .env
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.2"
          memory: '250M'
    environment:
      SERVICES: api
      PORT: 8800
    depends_on:
      - rabbitmq
    networks:
      - internal

  alertmanager:
    build:
      context: ./app
    env_file: .env
    environment:
      SERVICES: alertmanager
    depends_on:
      - rabbitmq
    networks:
      - internal

  ticketmessages:
    build:
      context: ./app
    env_file: .env
    environment:
      SERVICES: ticketMessages
    depends_on:
      - rabbitmq
    networks:
      - internal

  web:
    image: nginx
    restart: always
    volumes:
      - ./web/nginx:/etc/nginx/conf.d/
      - ./web/static:/usr/share/nginx/web
    ports:
      - 80:80
    networks:
      - internal

networks:
  internal:

volumes:
  data:
